# header: 
#   title: F per nuclide for (a,xd)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-18
#   format: YANDF-0.4
# reaction: 
#   type: (a,xd)
#   ENDF_MF: 3
#   ENDF_MT: 204
#   parameters: 
#     Number of sets: 6
#     Number of points: 6
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.367941E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 6
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
        7             14             -1             0.000000       1.275545       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       13             27             -1             0.000000       1.467896       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       28             58             -1             0.000000       1.304208       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       40             90             -1             0.000000       1.393639       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       83            209             -1             0.000000       1.525323       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       90            232             -1             0.000000       1.165451       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
