# header: 
#   title: F per nuclide for (a,xh)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-18
#   format: YANDF-0.4
# reaction: 
#   type: (a,xh)
#   ENDF_MF: 3
#   ENDF_MT: 206
#   parameters: 
#     Number of sets: 6
#     Number of points: 6
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.411345E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 6
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
        6             12             -1             0.000000       1.580388       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       13             27             -1             0.000000       1.421152       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       28             58             -1             0.000000       1.279530       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       40             90             -1             0.000000       1.754610       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       83            209             -1             0.000000       1.008705       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       90            232             -1             0.000000       1.049256       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
