# header: 
#   title: F per nuclide for (a,p)g
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-18
#   format: YANDF-0.4
# reaction: 
#   type: (a,p)g
#   ENDF_MF: 3
#   ENDF_MT: 103
#   parameters: 
#     Number of sets: 7
#     Number of points: 91
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.424562E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 36
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       40             92              0             0.000000       1.384435       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2             27
       42             92              0             0.000000       1.432887       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           4             61
       83            209              0             0.000000       1.590471       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              3
