# header: 
#   title: F per nuclide for (a,2p)g
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-18
#   format: YANDF-0.4
# reaction: 
#   type: (a,2p)g
#   ENDF_MF: 3
#   ENDF_MT: 111
#   parameters: 
#     Number of sets: 1
#     Number of points: 3
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.570143E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 10
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       41             93              0             0.000000       1.570143       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              3
