# header: 
#   title: F per nuclide for (d,2np)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-08-30
#   format: YANDF-0.4
# reaction: 
#   type: (d,2np)
#   ENDF_MF: 3
#   ENDF_MT: 41
#   parameters: 
#     Number of sets: 2
#     Number of points: 12
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.477102E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 2
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       28             58             -1             0.000000       1.468250       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              8
       33             75             -1             0.000000       1.494563       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              4
