# header: 
#   title: F per nuclide for (d,xt)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-08-30
#   format: YANDF-0.4
# reaction: 
#   type: (d,xt)
#   ENDF_MF: 3
#   ENDF_MT: 205
#   parameters: 
#     Number of sets: 10
#     Number of points: 49
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.956939E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  2.225098E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 6
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
        3              7             -1             0.000000       2.310247       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              9
        4              9             -1             0.000000       1.919240       0.000000       0.000000       1.468735       0.000000       0.000000       0.000000           3             32
       13             27             -1             0.000000       2.129334       0.000000       0.000000       1.478346       0.000000       0.000000       0.000000           2              3
       28             58             -1             0.000000       1.314919       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       40             90             -1             0.000000       1.353956       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       82            208             -1             0.000000       1.670532       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
