# header: 
#   title: F per nuclide for (d,x)n
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-05-13
#   format: YANDF-0.4
# reaction: 
#   type: (d,x)n
#   ENDF_MF: 3
#   ENDF_MT: 5
#   parameters: 
#     Number of sets: 9
#     Number of points: 81
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  2.073668E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 199
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       73            181              2             0.000000       1.932193       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2             26
       79            197              2             0.000000       2.242128       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              3
