# header: 
#   title: F per nuclide for (d,xa)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-08-30
#   format: YANDF-0.4
# reaction: 
#   type: (d,xa)
#   ENDF_MF: 3
#   ENDF_MT: 207
#   parameters: 
#     Number of sets: 10
#     Number of points: 16
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.636208E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  1.273221E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 5
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       13             27             -1             0.000000       1.190539       0.000000       0.000000       1.190463       0.000000       0.000000       0.000000           2              3
       23             51             -1             0.000000       1.432901       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              2
       28             58             -1             0.000000       2.378538       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       40             90             -1             0.000000       2.377148       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       82            208             -1             0.000000       2.225631       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
