# header: 
#   title: F per nuclide for (d,3n)m
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-08-30
#   format: YANDF-0.4
# reaction: 
#   type: (d,3n)m
#   ENDF_MF: 3
#   ENDF_MT: 17
#   parameters: 
#     Number of sets: 4
#     Number of points: 61
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.630849E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 23
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       42            100              1             0.000000       1.481610       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             31
       48            114              1             0.000000       1.705762       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              9
       81            203              1             0.000000       1.902160       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             11
       81            205              1             0.000000       1.679277       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             10
