# header: 
#   title: F per nuclide for (d,4n)g
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-07-16
#   format: YANDF-0.4
# reaction: 
#   type: (d,4n)g
#   ENDF_MF: 3
#   ENDF_MT: 37
#   parameters: 
#     Number of sets: 9
#     Number of points: 125
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.662173E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 19
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       33             75              0             0.000000       1.719203       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2             56
       53            127              0             0.000000       1.618563       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             26
       55            133              0             0.000000       2.144574       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              6
       79            197              0             0.000000       1.531640       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           4             32
       83            209              0             0.000000       1.369271       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              5
