# header: 
#   title: F per nuclide for (d,xh)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-07-16
#   format: YANDF-0.4
# reaction: 
#   type: (d,xh)
#   ENDF_MF: 3
#   ENDF_MT: 206
#   parameters: 
#     Number of sets: 5
#     Number of points: 5
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.349348E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  1.322070E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 5
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       13             27             -1             0.000000       1.195534       0.000000       0.000000       1.322070       0.000000       0.000000       0.000000           1              1
       28             58             -1             0.000000       1.147599       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       40             90             -1             0.000000       1.308574       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       82            208             -1             0.000000       1.556590       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       90            232             -1             0.000000       1.433897       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
