# header: 
#   title: F per nuclide for (d,a)g
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-07-16
#   format: YANDF-0.4
# reaction: 
#   type: (d,a)g
#   ENDF_MF: 3
#   ENDF_MT: 107
#   parameters: 
#     Number of sets: 4
#     Number of points: 28
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.317507E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 29
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       22             46              0             0.000000       1.298965       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             12
       26             54              0             0.000000       1.356368       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              9
       40             92              0             0.000000       1.323653       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              6
       48            106              0             0.000000       1.000113       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
