# header: 
#   title: F per nuclide for (d,xn)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-08-30
#   format: YANDF-0.4
# reaction: 
#   type: (d,xn)
#   ENDF_MF: 3
#   ENDF_MT: 201
#   parameters: 
#     Number of sets: 10
#     Number of points: 181
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.612098E+00
#     F for endfb8.1:  1.236480E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  1.348135E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 4
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
        3              6             -1             0.000000       1.914336       0.000000       0.000000       1.567799       0.000000       0.000000       0.000000           5             57
        3              7             -1             0.000000       1.470075       1.236480       0.000000       1.181720       0.000000       0.000000       0.000000           3             51
        4              9             -1             0.000000       1.426214       0.000000       0.000000       1.252163       0.000000       0.000000       0.000000           1             71
        8             16             -1             0.000000       1.821232       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              2
