# header: 
#   title: F per nuclide for (d,n')g
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-08-30
#   format: YANDF-0.4
# reaction: 
#   type: (d,n')g
#   ENDF_MF: 3
#   ENDF_MT: 4
#   parameters: 
#     Number of sets: 4
#     Number of points: 21
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.629862E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 38
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       42             94              0             0.000000       1.519199       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           3             15
       70            176              0             0.000000       1.879254       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              6
