# header: 
#   title: F per nuclide for (d,xp)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-05-13
#   format: YANDF-0.4
# reaction: 
#   type: (d,xp)
#   ENDF_MF: 3
#   ENDF_MT: 203
#   parameters: 
#     Number of sets: 6
#     Number of points: 10
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.305441E+00
#     F for endfb8.1:  1.116313E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  1.717654E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 6
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
        3              6             -1             0.000000       1.273612       0.000000       0.000000       1.705868       0.000000       0.000000       0.000000           1              5
       13             27             -1             0.000000       1.543202       0.000000       0.000000       1.764146       0.000000       0.000000       0.000000           1              1
       28             58             -1             0.000000       1.197982       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       40             90             -1             0.000000       1.040908       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       82            208             -1             0.000000       1.515099       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       90            232             -1             0.000000       1.163263       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
