# header: 
#   title: F per nuclide for (d,2p)g
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-08-30
#   format: YANDF-0.4
# reaction: 
#   type: (d,2p)g
#   ENDF_MF: 3
#   ENDF_MT: 111
#   parameters: 
#     Number of sets: 4
#     Number of points: 10
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.583094E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 15
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       33             75              0             0.000000       1.016083       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       47            109              0             0.000000       1.555457       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2              8
       53            127              0             0.000000       2.097598       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
