# header: 
#   title: F per nuclide for (d,n')m
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-05-13
#   format: YANDF-0.4
# reaction: 
#   type: (d,n')m
#   ENDF_MF: 3
#   ENDF_MT: 4
#   parameters: 
#     Number of sets: 5
#     Number of points: 33
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.920579E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 43
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       42             92              1             0.000000       1.460470       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              9
       42             94              1             0.000000       2.650347       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              2
       42             98              1             0.000000       2.226569       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              6
       48            114              1             0.000000       1.856962       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             14
       81            203              1             0.000000       2.484577       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              2
