# header: 
#   title: F per nuclide for (d,a)m
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-05-13
#   format: YANDF-0.4
# reaction: 
#   type: (d,a)m
#   ENDF_MF: 3
#   ENDF_MT: 107
#   parameters: 
#     Number of sets: 9
#     Number of points: 92
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.640937E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 35
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       18             36              1             0.000000       1.734586       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             13
       22             46              1             0.000000       1.401396       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             21
       26             54              1             0.000000       1.239567       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2             29
       42             94              1             0.000000       1.831102       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2             15
       42             97              1             0.000000       2.322896       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2              7
       52            122              1             0.000000       2.216156       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              7
