# header: 
#   title: F per nuclide for (g,a)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-18
#   format: YANDF-0.4
# reaction: 
#   type: (g,a)
#   ENDF_MF: 3
#   ENDF_MT: 107
#   parameters: 
#     Number of sets: 7
#     Number of points: 102
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.839047E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 5
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       23             51             -1             0.000000       1.573499       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2             48
       29             65             -1             0.000000       2.296901       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             24
       32             76             -1             0.000000       2.005995       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2             12
       37             87             -1             0.000000       1.660554       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             11
       40             96             -1             0.000000       1.873090       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              7
