# header: 
#   title: F per nuclide for (h,np)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-05-13
#   format: YANDF-0.4
# reaction: 
#   type: (h,np)
#   ENDF_MF: 3
#   ENDF_MT: 28
#   parameters: 
#     Number of sets: 9
#     Number of points: 81
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.694277E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 6
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
        5             10             -1             0.000000       1.701788       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              8
        6             12             -1             0.000000       1.562515       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           3             39
       26             56             -1             0.000000       1.871624       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             14
       30             64             -1             0.000000       1.696920       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2              6
       30             66             -1             0.000000       1.723110       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              9
       34             76             -1             0.000000       2.069657       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              5
