# header: 
#   title: F per nuclide for (h,g)g
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-05-13
#   format: YANDF-0.4
# reaction: 
#   type: (h,g)g
#   ENDF_MF: 3
#   ENDF_MT: 102
#   parameters: 
#     Number of sets: 1
#     Number of points: 3
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  2.268584E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 2
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       19             41              0             0.000000       2.268584       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              3
