# header: 
#   title: F per nuclide for (h,2n)m
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-07-16
#   format: YANDF-0.4
# reaction: 
#   type: (h,2n)m
#   ENDF_MF: 3
#   ENDF_MT: 16
#   parameters: 
#     Number of sets: 10
#     Number of points: 70
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  2.072271E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 29
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       35             81              1             0.000000       2.040884       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              8
       41             93              1             0.000000       2.078129       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           3             41
       45            103              1             0.000000       1.576542       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       47            107              1             0.000000       2.219049       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              3
       48            116              1             0.000000       1.992957       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              9
       79            197              1             0.000000       2.163244       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           3              8
