# header: 
#   title: F per nuclide for (h,2a)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-08-30
#   format: YANDF-0.4
# reaction: 
#   type: (h,2a)
#   ENDF_MF: 3
#   ENDF_MT: 108
#   parameters: 
#     Number of sets: 2
#     Number of points: 10
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.696748E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 2
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
        8             16             -1             0.000000       1.524001       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              9
       13             27             -1             0.000000       2.987292       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
