# header: 
#   title: F per nuclide for (h,xp)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-07-16
#   format: YANDF-0.4
# reaction: 
#   type: (h,xp)
#   ENDF_MF: 3
#   ENDF_MT: 203
#   parameters: 
#     Number of sets: 1
#     Number of points: 3
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.302651E+00
#     F for endfb8.1:  1.332063E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 1
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       28             58             -1             0.000000       1.302651       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              3
