# header: 
#   title: F per nuclide for (h,t)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-07-16
#   format: YANDF-0.4
# reaction: 
#   type: (h,t)
#   ENDF_MF: 3
#   ENDF_MT: 105
#   parameters: 
#     Number of sets: 3
#     Number of points: 45
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  2.505774E+00
#     F for endfb8.1:  1.272204E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 3
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
        5             10             -1             0.000000       2.442665       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             16
        5             11             -1             0.000000       2.539922       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       29             65             -1             0.000000       2.540551       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             28
