# header: 
#   title: F per nuclide for (h,2na)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-08-30
#   format: YANDF-0.4
# reaction: 
#   type: (h,2na)
#   ENDF_MF: 3
#   ENDF_MT: 24
#   parameters: 
#     Number of sets: 2
#     Number of points: 14
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.900968E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 2
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       27             59             -1             0.000000       1.748243       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             10
       41             93             -1             0.000000       2.258988       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              4
