# header: 
#   title: F per nuclide for (h,a)m
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-07-16
#   format: YANDF-0.4
# reaction: 
#   type: (h,a)m
#   ENDF_MF: 3
#   ENDF_MT: 107
#   parameters: 
#     Number of sets: 5
#     Number of points: 39
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.644604E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 15
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       17             35              1             0.000000       1.580897       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             11
       21             45              1             0.000000       1.255201       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             13
       47            107              1             0.000000       2.121541       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              4
       48            116              1             0.000000       1.634630       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              6
       79            197              1             0.000000       2.159056       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              5
