# header: 
#   title: F per nuclide for (h,p)g
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-07-16
#   format: YANDF-0.4
# reaction: 
#   type: (h,p)g
#   ENDF_MF: 3
#   ENDF_MT: 103
#   parameters: 
#     Number of sets: 2
#     Number of points: 17
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.407384E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 8
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       12             24              0             0.000000       1.556943       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             10
       38             88              0             0.000000       1.061878       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              7
