# header: 
#   title: F per nuclide for (n,na)m
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-18
#   format: YANDF-0.4
# reaction: 
#   type: (n,na)m
#   ENDF_MF: 3
#   ENDF_MT: 22
#   parameters: 
#     Number of sets: 7
#     Number of points: 20
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.405720E+00
#     F for endfb8.1:  1.597129E+00
#     F for jeff4.0:  1.489696E+00
#     F for jendl5.0:  1.385140E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  1.491542E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 17
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       40             91              1             0.000000       1.248940       1.597129       1.248940       1.129917       0.000000       1.308397       0.000000           1              5
       41             93              1             0.000000       1.196620       0.000000       1.429183       1.329565       0.000000       1.562719       0.000000           4              9
       45            103              1             0.000000       1.724679       0.000000       1.724679       1.599729       0.000000       1.513404       0.000000           2              6
