# header: 
#   title: F per nuclide for (n,n'_28)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-18
#   format: YANDF-0.4
# reaction: 
#   type: (n,n'_28)
#   ENDF_MF: 3
#   ENDF_MT: 78
#   parameters: 
#     Number of sets: 1
#     Number of points: 12
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.755749E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  2.015793E+00
#     F for jendl5.0:  1.829069E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 1
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       56            136             -1             0.000000       1.755749       0.000000       2.015793       1.829069       0.000000       0.000000       0.000000           1             12
