# header: 
#   title: F per nuclide for (n,n')n
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-18
#   format: YANDF-0.4
# reaction: 
#   type: (n,n')n
#   ENDF_MF: 3
#   ENDF_MT: 4
#   parameters: 
#     Number of sets: 3
#     Number of points: 7
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.703497E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  2.369128E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 92
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       72            178              2             0.000000       1.253783       0.000000       2.111128       0.000000       0.000000       0.000000       0.000000           1              2
       72            179              2             0.000000       1.847500       0.000000       2.470785       0.000000       0.000000       0.000000       0.000000           2              5
