# header: 
#   title: F per nuclide for (n,xt)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-18
#   format: YANDF-0.4
# reaction: 
#   type: (n,xt)
#   ENDF_MF: 3
#   ENDF_MT: 205
#   parameters: 
#     Number of sets: 4
#     Number of points: 39
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  2.096427E+00
#     F for endfb8.1:  1.248636E+00
#     F for jeff4.0:  1.146273E+00
#     F for jendl5.0:  1.346452E+00
#     F for cendl3.2:  1.250708E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 3
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
        4              9             -1             0.000000       2.139753       1.248636       1.146273       1.354897       1.248635       0.000000       0.000000           2             36
        5             10             -1             0.000000       1.180255       0.000000       0.000000       1.202149       1.288108       0.000000       0.000000           1              1
        6             12             -1             0.000000       1.657826       0.000000       0.000000       1.327083       0.000000       0.000000       0.000000           1              2
