# header: 
#   title: F per nuclide for (n,n'_29)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-18
#   format: YANDF-0.4
# reaction: 
#   type: (n,n'_29)
#   ENDF_MF: 3
#   ENDF_MT: 79
#   parameters: 
#     Number of sets: 3
#     Number of points: 18
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.643283E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  1.815409E+00
#     F for jendl5.0:  2.702058E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 2
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       41             93             -1             0.000000       1.412152       0.000000       1.663645       0.000000       0.000000       0.000000       0.000000           1             14
       62            154             -1             0.000000       2.299420       0.000000       2.299420       2.702058       0.000000       0.000000       0.000000           2              4
