# header: 
#   title: F per nuclide for (n,n')g
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-18
#   format: YANDF-0.4
# reaction: 
#   type: (n,n')g
#   ENDF_MF: 3
#   ENDF_MT: 4
#   parameters: 
#     Number of sets: 2
#     Number of points: 80
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.491602E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  1.491602E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 60
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       45            103              0             0.000000       1.197608       0.000000       1.197608       0.000000       0.000000       0.000000       0.000000           1             39
       47            109              0             0.000000       1.699141       0.000000       1.699141       0.000000       0.000000       0.000000       0.000000           1             41
