# header: 
#   title: F per nuclide for (n,n'_08)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-18
#   format: YANDF-0.4
# reaction: 
#   type: (n,n'_08)
#   ENDF_MF: 3
#   ENDF_MT: 58
#   parameters: 
#     Number of sets: 6
#     Number of points: 131
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.357527E+00
#     F for endfb8.1:  1.297074E+00
#     F for jeff4.0:  1.289624E+00
#     F for jendl5.0:  1.267701E+00
#     F for cendl3.2:  1.509922E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 5
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       16             32             -1             0.000000       2.565376       0.000000       2.565376       0.000000       0.000000       0.000000       0.000000           1              1
       26             56             -1             0.000000       1.289853       1.265339       1.265339       1.309955       1.743908       0.000000       0.000000           1             52
       57            139             -1             0.000000       2.523570       1.954127       2.523570       2.203412       1.799243       0.000000       0.000000           1              4
       62            154             -1             0.000000       1.248261       0.000000       1.248261       1.711408       1.451670       0.000000       0.000000           2             12
       82            206             -1             0.000000       1.287758       1.276269       1.115649       1.000000       1.251418       0.000000       0.000000           1             62
