# header: 
#   title: F per nuclide for (n,2np)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-18
#   format: YANDF-0.4
# reaction: 
#   type: (n,2np)
#   ENDF_MF: 3
#   ENDF_MT: 41
#   parameters: 
#     Number of sets: 1
#     Number of points: 8
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  2.256488E+00
#     F for endfb8.1:  1.385186E+00
#     F for jeff4.0:  2.256488E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  2.195266E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 1
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       42             92             -1             0.000000       2.256488       0.000000       2.256488       0.000000       0.000000       2.195266       0.000000           1              8
