# header: 
#   title: F per nuclide for (n,p)n
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-18
#   format: YANDF-0.4
# reaction: 
#   type: (n,p)n
#   ENDF_MF: 3
#   ENDF_MT: 103
#   parameters: 
#     Number of sets: 8
#     Number of points: 23
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.266771E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  1.224253E+00
#     F for jendl5.0:  1.337544E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  1.245674E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 315
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       30             70              2             0.000000       1.386180       0.000000       1.240960       1.001032       0.000000       0.000000       0.000000           1              1
       48            116              2             0.000000       1.321736       0.000000       1.321736       0.000000       0.000000       0.000000       0.000000           1              1
       50            118              2             0.000000       1.678897       0.000000       1.678897       1.005717       0.000000       1.005666       0.000000           1              1
       50            120              2             0.000000       1.044126       0.000000       1.044126       1.455390       0.000000       1.043387       0.000000           1              6
       50            122              2             0.000000       1.075562       0.000000       1.075562       1.001712       0.000000       1.753127       0.000000           1              1
       74            182              2             0.000000       1.284859       0.000000       0.000000       1.306172       0.000000       1.268561       0.000000           3             13
