# header: 
#   title: F per nuclide for (p,4n)m
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-18
#   format: YANDF-0.4
# reaction: 
#   type: (p,4n)m
#   ENDF_MF: 3
#   ENDF_MT: 37
#   parameters: 
#     Number of sets: 6
#     Number of points: 74
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.424639E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 42
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       38             88              1             0.000000       1.501503       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              8
       42             96              1             0.000000       2.477047       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       48            116              1             0.000000       1.555634       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              9
       81            205              1             0.000000       1.362863       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           3             56
