# header: 
#   title: F per nuclide for (p,d)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-18
#   format: YANDF-0.4
# reaction: 
#   type: (p,d)
#   ENDF_MF: 3
#   ENDF_MT: 104
#   parameters: 
#     Number of sets: 3
#     Number of points: 58
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.776114E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 2
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
        4              9             -1             0.000000       1.752511       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2             57
       92            238             -1             0.000000       2.984850       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
