# header: 
#   title: F per nuclide for (p,p)m
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-18
#   format: YANDF-0.4
# reaction: 
#   type: (p,p)m
#   ENDF_MF: 3
#   ENDF_MT: 103
#   parameters: 
#     Number of sets: 7
#     Number of points: 59
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.836550E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 18
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       43             99              1             0.000000       2.106952       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             25
       48            111              1             0.000000       1.239132       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              4
       49            113              1             0.000000       1.782637       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2             13
       49            115              1             0.000000       1.562833       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           3             17
