# header: 
#   title: F per nuclide for (t,xn)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-07-16
#   format: YANDF-0.4
# reaction: 
#   type: (t,xn)
#   ENDF_MF: 3
#   ENDF_MT: 201
#   parameters: 
#     Number of sets: 8
#     Number of points: 174
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.397641E+00
#     F for endfb8.1:  2.051389E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 4
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
        3              6             -1             0.000000       1.405802       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           3             38
        3              7             -1             0.000000       1.334554       2.591308       0.000000       0.000000       0.000000       0.000000       0.000000           3             94
        4              9             -1             0.000000       1.499714       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             37
        9             19             -1             0.000000       1.627955       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              5
