# header: 
#   title: F per nuclide for (t,p)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-07-16
#   format: YANDF-0.4
# reaction: 
#   type: (t,p)
#   ENDF_MF: 3
#   ENDF_MT: 103
#   parameters: 
#     Number of sets: 8
#     Number of points: 1268
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.963893E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 5
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
        3              6             -1             0.000000       1.997701       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1            336
        3              7             -1             0.000000       1.918045       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           3            654
        5             10             -1             0.000000       1.827141       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             33
        5             11             -1             0.000000       2.059570       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2            241
        6             12             -1             0.000000       1.843215       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              4
