# header: 
#   title: F per nuclide for (t,n')
#   source: EXFOR
#   user: Arjan Koning
#   date: 2026-07-16
#   format: YANDF-0.4
# reaction: 
#   type: (t,n')
#   ENDF_MF: 3
#   ENDF_MT: 4
#   parameters: 
#     Number of sets: 3
#     Number of points: 25
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.613267E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 2
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
        4              9             -1             0.000000       1.395410       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             12
        8             16             -1             0.000000       1.787574       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2             13
