# header: 
#   title: F per nucleus summed over all reactions for heavyion
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-01
#   format: YANDF-0.4
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 0
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
