# header: 
#   title: F per nuclide for (a,a)m
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-10-25
#   format: YANDF-0.4
# reaction: 
#   type: (a,a)m
#   ENDF_MF: 3
#   ENDF_MT: 107
#   parameters: 
#     Number of sets: 3
#     Number of points: 15
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.891909E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 3
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       48            111              1             0.000000       1.905952       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              8
       49            115              1             0.000000       1.875786       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2              7
