# header: 
#   title: F per nuclide for (a,p)m
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-01
#   format: YANDF-0.4
# reaction: 
#   type: (a,p)m
#   ENDF_MF: 3
#   ENDF_MT: 103
#   parameters: 
#     Number of sets: 10
#     Number of points: 92
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.661646E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 41
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       40             92              1             0.000000       1.849876       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2             23
       42             92              1             0.000000       1.549848       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           3             46
       44             96              1             0.000000       1.354593       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2              6
       50            117              1             0.000000       1.709867       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2             14
       83            209              1             0.000000       2.080103       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              3
