# header: 
#   title: F per nuclide for (a,4n)g
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-01
#   format: YANDF-0.4
# reaction: 
#   type: (a,4n)g
#   ENDF_MF: 3
#   ENDF_MT: 37
#   parameters: 
#     Number of sets: 7
#     Number of points: 47
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.659639E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 50
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       39             89              0             0.000000       1.409554       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2              9
       41             93              0             0.000000       1.885520       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              7
       45            103              0             0.000000       2.267644       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              3
       63            151              0             0.000000       1.621536       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             23
       65            159              0             0.000000       1.351320       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              4
       79            197              0             0.000000       1.939291       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
