# header: 
#   title: F per nuclide for (a,na)g
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-01
#   format: YANDF-0.4
# reaction: 
#   type: (a,na)g
#   ENDF_MF: 3
#   ENDF_MT: 22
#   parameters: 
#     Number of sets: 8
#     Number of points: 30
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.585502E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 33
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       21             45              0             0.000000       1.482746       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           3             18
       35             81              0             0.000000       1.134913       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
       45            103              0             0.000000       1.821914       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           2              3
       48            116              0             0.000000       1.481313       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              4
       50            124              0             0.000000       1.980165       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              4
