# header: 
#   title: F per nuclide for (g,4n)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-10-25
#   format: YANDF-0.4
# reaction: 
#   type: (g,4n)
#   ENDF_MF: 3
#   ENDF_MT: 37
#   parameters: 
#     Number of sets: 1
#     Number of points: 39
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.849190E+00
#     F for endfb8.1:  1.646039E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  1.633787E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 1
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       67            165             -1             0.000000       1.849190       1.646039       0.000000       1.633787       0.000000       0.000000       0.000000           1             39
