# header: 
#   title: F per nuclide for (g,n')m
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-01
#   format: YANDF-0.4
# reaction: 
#   type: (g,n')m
#   ENDF_MF: 3
#   ENDF_MT: 4
#   parameters: 
#     Number of sets: 3
#     Number of points: 28
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.687384E+00
#     F for endfb8.1:  2.021539E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 81
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       19             39              1             0.000000       1.777762       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             18
       36             86              1             0.000000       1.835419       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              4
       73            181              1             0.000000       1.216449       2.021539       0.000000       0.000000       0.000000       0.000000       0.000000           1              6
