# header: 
#   title: F per nuclide for (g,x)m
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-10-25
#   format: YANDF-0.4
# reaction: 
#   type: (g,x)m
#   ENDF_MF: 3
#   ENDF_MT: 5
#   parameters: 
#     Number of sets: 7
#     Number of points: 98
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.769398E+00
#     F for endfb8.1:  1.871640E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  1.762130E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 122
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       19             39              1             0.000000       1.777762       1.641895       0.000000       1.641895       0.000000       0.000000       0.000000           1             18
       36             86              1             0.000000       1.835419       0.000000       0.000000       1.384420       0.000000       0.000000       0.000000           1              4
       40             90              1             0.000000       1.799181       0.000000       0.000000       1.784931       0.000000       0.000000       0.000000           1             23
       49            115              1             0.000000       2.095610       2.308253       0.000000       1.968193       0.000000       0.000000       0.000000           2             10
       67            165              1             0.000000       1.718182       0.000000       0.000000       1.696825       0.000000       0.000000       0.000000           1             37
       73            181              1             0.000000       1.216449       0.000000       0.000000       1.162160       0.000000       0.000000       0.000000           1              6
