# header: 
#   title: F per nuclide for (g,n')g
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-01
#   format: YANDF-0.4
# reaction: 
#   type: (g,n')g
#   ENDF_MF: 3
#   ENDF_MT: 4
#   parameters: 
#     Number of sets: 1
#     Number of points: 6
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.254743E+00
#     F for endfb8.1:  1.154586E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 78
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       73            181              0             0.000000       1.254743       1.154586       0.000000       0.000000       0.000000       0.000000       0.000000           1              6
