# header: 
#   title: F per nuclide for (g,g)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-10-25
#   format: YANDF-0.4
# reaction: 
#   type: (g,g)
#   ENDF_MF: 3
#   ENDF_MT: 102
#   parameters: 
#     Number of sets: 2
#     Number of points: 16
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.837035E+00
#     F for endfb8.1:  1.661940E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  1.686210E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 2
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       52            130             -1             0.000000       1.715190       1.591882       0.000000       1.591882       0.000000       0.000000       0.000000           1              9
       56            138             -1             0.000000       1.986511       1.836941       0.000000       1.805024       0.000000       0.000000       0.000000           1              7
