# header: 
#   title: F per nuclide for (n,pa)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-10-25
#   format: YANDF-0.4
# reaction: 
#   type: (n,pa)
#   ENDF_MF: 3
#   ENDF_MT: 112
#   parameters: 
#     Number of sets: 6
#     Number of points: 27
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.710726E+00
#     F for endfb8.1:  2.029638E+00
#     F for jeff4.0:  1.538311E+00
#     F for jendl5.0:  1.409043E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  1.358737E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 3
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       25             55             -1             0.000000       1.851488       0.000000       0.000000       0.000000       0.000000       1.240035       0.000000           2              8
       28             58             -1             0.000000       1.550044       2.029638       1.538311       1.468953       0.000000       1.486636       0.000000           3             15
       29             63             -1             0.000000       1.980063       0.000000       0.000000       1.198459       0.000000       1.339547       0.000000           1              4
