# header: 
#   title: F per nuclide for (n,n'_11)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-10-25
#   format: YANDF-0.4
# reaction: 
#   type: (n,n'_11)
#   ENDF_MF: 3
#   ENDF_MT: 61
#   parameters: 
#     Number of sets: 1
#     Number of points: 8
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.690085E+00
#     F for endfb8.1:  1.393900E+00
#     F for jeff4.0:  1.690085E+00
#     F for jendl5.0:  1.520862E+00
#     F for cendl3.2:  1.823601E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 1
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       55            133             -1             0.000000       1.690085       1.334279       1.690085       1.523565       0.000000       0.000000       0.000000           1              8
