# header: 
#   title: F per nuclide for (n,t)g
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-10-25
#   format: YANDF-0.4
# reaction: 
#   type: (n,t)g
#   ENDF_MF: 3
#   ENDF_MT: 105
#   parameters: 
#     Number of sets: 2
#     Number of points: 2
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.690278E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  2.219903E+00
#     F for jendl5.0:  1.014815E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  1.568477E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 21
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       20             40              0             0.000000       1.329241       0.000000       1.339556       0.000000       0.000000       1.190254       0.000000           1              1
       59            141              0             0.000000       1.984928       0.000000       2.972002       0.000000       0.000000       0.000000       0.000000           1              1
