# header: 
#   title: F per nuclide for (n,2na)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-01
#   format: YANDF-0.4
# reaction: 
#   type: (n,2na)
#   ENDF_MF: 3
#   ENDF_MT: 24
#   parameters: 
#     Number of sets: 6
#     Number of points: 12
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.657013E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  1.976213E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  1.281090E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 2
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       27             59             -1             0.000000       1.069992       0.000000       0.000000       0.000000       0.000000       1.325288       0.000000           2              2
       41             93             -1             0.000000       1.737401       0.000000       1.976213       0.000000       0.000000       1.269317       0.000000           4             10
