# header: 
#   title: F per nuclide for (n,xd)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-10-25
#   format: YANDF-0.4
# reaction: 
#   type: (n,xd)
#   ENDF_MF: 3
#   ENDF_MT: 204
#   parameters: 
#     Number of sets: 8
#     Number of points: 9
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.317183E+00
#     F for endfb8.1:  1.448194E+00
#     F for jeff4.0:  1.489474E+00
#     F for jendl5.0:  1.536349E+00
#     F for cendl3.2:  1.097267E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 3
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
        6             12             -1             0.000000       1.275061       1.612970       1.612970       1.462411       0.000000       0.000000       0.000000           2              3
       41             93             -1             0.000000       1.074281       1.000025       1.421419       1.000008       1.071342       0.000000       0.000000           2              2
       42             95             -1             0.000000       1.533746       0.000000       1.533746       1.142043       1.005716       0.000000       0.000000           2              2
