# header: 
#   title: F per nuclide for (n,a)n
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-10-25
#   format: YANDF-0.4
# reaction: 
#   type: (n,a)n
#   ENDF_MF: 3
#   ENDF_MT: 107
#   parameters: 
#     Number of sets: 2
#     Number of points: 2
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.001092E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  1.001455E+00
#     F for jendl5.0:  1.005185E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  1.583824E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 207
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       53            127              2             0.000000       1.001455       0.000000       1.001455       1.005185       0.000000       1.713849       0.000000           1              1
       74            182              2             0.000000       1.000517       0.000000       0.000000       0.000000       0.000000       1.514071       0.000000           1              1
