# header: 
#   title: F per nuclide for (n,n'_13)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-01
#   format: YANDF-0.4
# reaction: 
#   type: (n,n'_13)
#   ENDF_MF: 3
#   ENDF_MT: 63
#   parameters: 
#     Number of sets: 2
#     Number of points: 10
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.705163E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  2.662909E+00
#     F for cendl3.2:  2.056746E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 1
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       26             54             -1             0.000000       1.705163       0.000000       0.000000       2.775924       2.038481       0.000000       0.000000           2             10
