# header: 
#   title: F per nuclide for (n,t)m
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-01
#   format: YANDF-0.4
# reaction: 
#   type: (n,t)m
#   ENDF_MF: 3
#   ENDF_MT: 105
#   parameters: 
#     Number of sets: 3
#     Number of points: 3
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  2.327872E+00
#     F for endfb8.1:  1.239703E+00
#     F for jeff4.0:  2.165393E+00
#     F for jendl5.0:  1.327181E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  1.449530E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 22
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       57            139              1             0.000000       2.327872       1.239703       2.327872       1.216207       0.000000       1.254191       0.000000           3              3
