# header: 
#   title: F per nuclide for (n,4n)g
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-01
#   format: YANDF-0.4
# reaction: 
#   type: (n,4n)g
#   ENDF_MF: 3
#   ENDF_MT: 37
#   parameters: 
#     Number of sets: 4
#     Number of points: 4
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.525705E+00
#     F for endfb8.1:  1.069546E+00
#     F for jeff4.0:  1.460898E+00
#     F for jendl5.0:  1.277932E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  1.139372E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 16
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       71            175              0             0.000000       1.525705       0.000000       1.525705       1.214002       0.000000       1.141943       0.000000           4              4
