# header: 
#   title: F per nuclide for (n,p_04)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-10-25
#   format: YANDF-0.4
# reaction: 
#   type: (n,p_04)
#   ENDF_MF: 3
#   ENDF_MT: 804
#   parameters: 
#     Number of sets: 0
#     Number of points: 0
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  0.000000E+00
#     F for endfb8.1:  1.231066E+00
#     F for jeff4.0:  1.231066E+00
#     F for jendl5.0:  1.251555E+00
#     F for cendl3.2:  1.231066E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 0
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
