# header: 
#   title: F per nuclide for (n,n'_10)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-01
#   format: YANDF-0.4
# reaction: 
#   type: (n,n'_10)
#   ENDF_MF: 3
#   ENDF_MT: 60
#   parameters: 
#     Number of sets: 2
#     Number of points: 61
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.399805E+00
#     F for endfb8.1:  1.340074E+00
#     F for jeff4.0:  1.217884E+00
#     F for jendl5.0:  1.071856E+00
#     F for cendl3.2:  1.067141E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 2
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       26             56             -1             0.000000       1.197646       1.193861       1.193861       1.179091       0.000000       0.000000       0.000000           1             11
       82            206             -1             0.000000       1.435813       1.367872       1.222910       1.000000       1.067141       0.000000       0.000000           1             50
