# header: 
#   title: F per nuclide for (n,2p)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-01
#   format: YANDF-0.4
# reaction: 
#   type: (n,2p)
#   ENDF_MF: 3
#   ENDF_MT: 111
#   parameters: 
#     Number of sets: 2
#     Number of points: 12
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.457166E+00
#     F for endfb8.1:  2.152202E+00
#     F for jeff4.0:  1.377143E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  1.722617E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 2
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       23             51             -1             0.000000       1.757237       0.000000       1.554673       0.000000       0.000000       1.614292       0.000000           1              3
       42             92             -1             0.000000       1.334029       2.152202       1.334029       0.000000       0.000000       1.763254       0.000000           1              9
