# header: 
#   title: F per nuclide for (n,2n)n
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-01
#   format: YANDF-0.4
# reaction: 
#   type: (n,2n)n
#   ENDF_MF: 3
#   ENDF_MT: 16
#   parameters: 
#     Number of sets: 26
#     Number of points: 85
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.386993E+00
#     F for endfb8.1:  2.367403E+00
#     F for jeff4.0:  1.417932E+00
#     F for jendl5.0:  1.227923E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  1.322696E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 309
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       63            153              2             0.000000       1.559690       0.000000       1.559690       1.236472       0.000000       1.260188       0.000000           8             15
       72            180              2             0.000000       1.454888       0.000000       0.000000       1.236867       0.000000       1.326367       0.000000           3              6
       77            191              2             0.000000       1.310042       2.367403       1.310042       1.203152       0.000000       1.496810       0.000000          10             55
       77            193              2             0.000000       1.073374       0.000000       1.073374       1.048167       0.000000       1.093347       0.000000           4              4
       79            197              2             0.000000       1.651475       0.000000       0.000000       1.244193       0.000000       1.257199       0.000000           1              5
