# header: 
#   title: F per nuclide for (n,n'_19)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-10-25
#   format: YANDF-0.4
# reaction: 
#   type: (n,n'_19)
#   ENDF_MF: 3
#   ENDF_MT: 69
#   parameters: 
#     Number of sets: 6
#     Number of points: 54
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.821109E+00
#     F for endfb8.1:  1.989011E+00
#     F for jeff4.0:  1.508077E+00
#     F for jendl5.0:  2.064034E+00
#     F for cendl3.2:  2.018053E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 4
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       41             93             -1             0.000000       1.391558       1.575878       1.344307       0.000000       0.000000       0.000000       0.000000           1             17
       54            134             -1             0.000000       2.047408       2.133149       2.047407       0.000000       0.000000       0.000000       0.000000           1              7
       62            154             -1             0.000000       1.220841       0.000000       1.220841       0.000000       1.670254       0.000000       0.000000           2              8
       92            238             -1             0.000000       2.197368       2.196466       0.000000       2.064034       2.653968       0.000000       0.000000           2             22
