# header: 
#   title: F per nuclide for (n,3n)g
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-01
#   format: YANDF-0.4
# reaction: 
#   type: (n,3n)g
#   ENDF_MF: 3
#   ENDF_MT: 17
#   parameters: 
#     Number of sets: 8
#     Number of points: 29
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.408564E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  1.416345E+00
#     F for jendl5.0:  1.602312E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  1.465332E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 41
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       39             89              0             0.000000       1.224673       0.000000       1.249356       2.192569       0.000000       1.218958       0.000000           4             13
       45            103              0             0.000000       1.610488       0.000000       1.610488       1.204013       0.000000       1.451242       0.000000           1              7
       47            107              0             0.000000       1.525681       0.000000       1.525681       1.059084       0.000000       1.204433       0.000000           2              2
       47            109              0             0.000000       1.437744       0.000000       1.437744       1.398172       0.000000       1.705892       0.000000           1              7
