# header: 
#   title: F per nuclide for (p,a)g
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-10-25
#   format: YANDF-0.4
# reaction: 
#   type: (p,a)g
#   ENDF_MF: 3
#   ENDF_MT: 107
#   parameters: 
#     Number of sets: 2
#     Number of points: 29
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.440719E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 53
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       22             47              0             0.000000       1.154306       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             16
       40             90              0             0.000000       1.684747       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1             13
