# header: 
#   title: F per nuclide for (p,4n)g
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-10-25
#   format: YANDF-0.4
# reaction: 
#   type: (p,4n)g
#   ENDF_MF: 3
#   ENDF_MT: 37
#   parameters: 
#     Number of sets: 5
#     Number of points: 137
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.693136E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  1.932908E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 38
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       25             55              0             0.000000       1.690548       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           3            133
       38             88              0             0.000000       1.324284       0.000000       0.000000       1.932908       0.000000       0.000000       0.000000           1              3
       42             96              0             0.000000       2.835875       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
