# header: 
#   title: F per nuclide for (p,2p)m
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-12-01
#   format: YANDF-0.4
# reaction: 
#   type: (p,2p)m
#   ENDF_MF: 3
#   ENDF_MT: 111
#   parameters: 
#     Number of sets: 2
#     Number of points: 5
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.421865E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  0.000000E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 16
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       42             92              1             0.000000       1.157652       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              4
       42             96              1             0.000000       2.076198       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              1
