# header: 
#   title: F per nuclide for (p,xh)
#   source: EXFOR
#   user: Arjan Koning
#   date: 2025-10-25
#   format: YANDF-0.4
# reaction: 
#   type: (p,xh)
#   ENDF_MF: 3
#   ENDF_MT: 206
#   parameters: 
#     Number of sets: 10
#     Number of points: 86
#     F for TALYS:  0.000000E+00
#     F for tendl.2025:  1.917931E+00
#     F for endfb8.1:  0.000000E+00
#     F for jeff4.0:  0.000000E+00
#     F for jendl5.0:  1.686403E+00
#     F for cendl3.2:  0.000000E+00
#     F for eaf.2010:  0.000000E+00
#     F for irdff2.0:  0.000000E+00
#   quantity: 
#     type: F
#   datablock: 
#     columns: 13
#     entries: 2
##       Z              A             iso           TALYS       tendl.2025      endfb8.1        jeff4.0       jendl5.0       cendl3.2       eaf.2010       irdff2.0         sets          points
##      []             []             []             []             []             []             []             []             []             []             []             []             []
       13             27             -1             0.000000       1.969877       0.000000       0.000000       1.671299       0.000000       0.000000       0.000000           2             24
       83            209             -1             0.000000       1.734008       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000           1              5
